### ISSUE TITLE
Tiralabra peer review #2

### ISSUE THREAD

**Issue by Sendouc** [emsknock/binder#2]
*Fetched 7th October around 12:05PM.*

`npm start` is missing and no instructions so assuming the program is not really meant be to ran by others just yet. Ran tests via `npm test` and all the tests seems to pass. A lot of tests which is nice!

  I'm a fan of the concept. Not an expert of compression algorithms but at least in the context of this course it adds utility to the end result when you are choosing the best out of the two algorithms like you do.

Code seems to be really well commented. That certainly makes it easier to understand this kind of project where you might not be that familiar what's going on without knowing the algorithms being implemented.

I was surprised to see `do...while` kind of loop being used. Had to actually Google the difference. I'm assuming the usage in `private fillHuffmanTree ()` is just an elegant solution. 

Here is another case of `do...while` that makes me more suspicious: https://github.com/emsknock/binder/blob/a2198de5c58e57d75dd4d03d50140fcb630269cf/src/compressors/lzw/index.ts#L27 Say  `reader.bytesLeft() === 0` when you call `compress()` do you still really want the loop to go through once? Might very easily be something here that I missed but this at least gave me a pause.  

https://github.com/emsknock/binder/blob/a2198de5c58e57d75dd4d03d50140fcb630269cf/src/structures/priority-queue/index.ts#L22 from quick visit to Google it seems this is equivalent to `Math.trunc()`. In a less performance critical code I think using a self-documenting function is better than some trick + commenting what the trick does but maybe it's about optimisation here.

 The structure of the project seems really solid. Although for my own taste having separate folder and 3 files for just three different types compared to simply having types.ts file seems like an overkill.   This hugely again comes down to preference but I'm not a fan of these sort of helper functions: https://github.com/emsknock/binder/blob/master/src/utils/bytes-chars/index.ts   The reason is that say we have char `c` and I see `charToByte(c)` being called. 

Yes in a sense you can guess what might be happening but maybe the person who implemented this function has a way different idea about what `charToByte` function should do than you so either way you need to double check.   Compare that to just using the oneliner of standard library that you can kind of expect everyone to be able to read.

------

This project really feels like a 5/5 in the making to me. Very little to nitpick even when trying to find something to comment on really hard. Good job all around!

**Comment by emsknock** [comment]
Thank you for the feedback and kind words!

Your assumption about the program not being runnable was correct: no logic for filesystem I/O etc is implemented yet.

---

Cheers for pointing out the possible confusion the (admittedly rare) `do ... while` loops can cause. I should probably test wether I am actually getting any time savings using them compared to the traditional `while` loops. The reason behind their use here is just micro-optimisation: all the loops used in the program need to be run at least once, so the initial loop condition check _can_ be skipped. Even in the LZW compressor situation you pointed out, `reader.bytesLeft()` will never equal `0` right after calling `compress()` since the compressor only accepts non-empty buffers in the constructor. I will be clarifying this in comments next to the loops in the code.

I agree with you about the double tilde trick and it isn't something I'd normally use. It's here mainly due to the course FAQ [telling us not to use the Math library](https://tiralabra.github.io/2020_p1/en/faq/#may-i-use-the-math-functions-in-java) — while the FAQ is talking about Java specifically, the situation is exactly the same for JS too. I hadn't heard of `Math.trunc` before, so I'll be adding that to my arsenal outside of this project, though!

The typings having their own folder is, like you say, overkill — I was preparing for the interfaces to grow, and was prematurely worried about that becoming an issue with them sharing a file from the get-go. It's now clear that the interfaces won't become more complex, and there's no reason **not** to merge them. The `ByteList` type alias might even be so specific that I should remove it completely.

And finally, the `charToByte` and `byteToChar` helpers: they were actually used for prototyping (the final logic shouldn't use mutable strings at all anyways, since they're a data structure too) and will be removed as soon as I finish the LZW inflator (i.e. the only place they're referenced). However, I do get your wider point about functions like that in general — to guarantee that all the contributors understand how they work, they should have their own documentation comments, which is definitely a lot more work than a one-liner from the std.
